### ISSUE TITLE
Can't getAuthToken and getUserProfile in the same time.

### ISSUE THREAD

**Issue by alvinraa** [nayanAubie/signin_with_linkedin#4]
When I attempt to retrieve both the AuthToken and UserProfile simultaneously, I am unable to obtain the AuthToken. I must comment out the UserProfile retrieval in order to successfully obtain the AuthToken.

I've explored an alternative approach, which involves calling the signIn function twice: once for the AuthToken and another time for the UserProfile. However, this method results in an unusual user experience (UX) behavior where the authentication popup appears twice.

here my code
![image](https://github.com/nayanAubie/signin_with_linkedin/assets/36125141/35df8197-d191-422e-9a17-f016e98e5537)

**Comment by nayanaubie** [comment]
@alvinraa Sure, I'll update

**Comment by nayanaubie** [comment]
Fixed with version - `0.0.3`
