### ISSUE TITLE
Support flutter-web

### ISSUE THREAD

**Issue by beheobong** [nayanAubie/signin_with_linkedin#6]
I checked signin_with_linkedin does not support flutter-web. Can you update and support it?

**Comment by nayanaubie** [comment]
Sure @beheobong. give me some time. thanks

**Comment by beheobong** [comment]
> Sure @beheobong. give me some time. thanks

Can you guide me? I will code and create merge request if I success

**Comment by nayanaubie** [comment]
@beheobong Fork the repository,
run the below command to create a `web` folder within the directory.

```sh
flutter create --platforms=web .
```

I hope existing code should work on the web too.

**Comment by beheobong** [comment]
@nayanAubie I tried. the sign_with_linkedin depend on webview_flutter that does not support flutter-web. So the web is not working. Do you have any idea?

**Comment by nayanaubie** [comment]
@beheobong I'm not sure about that. I need to check. I'll update you.

**Comment by beheobong** [comment]
> @beheobong I'm not sure about that. I need to check. I'll update you.

thanks you so much. I'll wait a good news from you. Have a nice day!
